### ISSUE TITLE
set body on put

### ISSUE THREAD

**Issue by ghost** [php-mod/curl#16]
how do you set the Curl body on put? I want to send a json body as part of my request to the endpoint and I don't see an "setBody" option of sorts.

**Comment by zurborg** [comment]
I think #21 addresses this issue. A body should be set with the second argument:

```php
$curl->put($url, $payload);
```

**Comment by nadar** [comment]
I am going to close this issue because:

- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.
