### ISSUE TITLE
php 5.2 works?

### ISSUE THREAD

**Issue by cargie** [php-mod/curl#34]
just want to know if it works with php 5.2?

**Comment by halfer** [comment]
@cargie: the minimum specified version is 5.3.0 in the Composer file. At this stage you should be using 5.6 minimum, though I appreciate some distros will still have 5.5. Version 5.2 is definitely dead and buried though - why are you still using that?

**Comment by cargie** [comment]
it's a requirement to support what wordpress supports. thanks

**Comment by halfer** [comment]
IMO, there's no need to run WordPress on anything other than a supported version.

**Comment by cargie** [comment]
wordpress supports php5.2. :(

**Comment by halfer** [comment]
They need to fix that as well! :smile_cat:
