### ISSUE TITLE
Add Travis badge to GitHub README

### ISSUE THREAD

**Issue by halfer** [php-mod/curl#37]
Nice to see this library is covered with Travis. Would it be possible to add a build badge to the README for this?

Looks like some fixing is necessary anyway - [PHP 7 and HHVM builds are broken](https://travis-ci.org/php-mod/curl/builds/193152488) presently.

**Comment by nadar** [comment]
I recommend that as well, but the tests should be fixed first, otherwise it looks a bit untrustworthy.

**Comment by nadar** [comment]
travis tests still broke => https://travis-ci.org/php-mod/curl

**Comment by nadar** [comment]
https://github.com/php-mod/curl/commit/ba385e40c5907850c555db24505c127fe29f1e44
