### ISSUE TITLE
why depricate _exec

### ISSUE THREAD

**Issue by mzummo** [php-mod/curl#39]
I am using this class for doing SFTP upload/download (i have found that curl is the most reliable method of doing this as opposed to other methods within PHP. Which on some servers seem to have issues.Since i am not using any standard put/delete/get I am using _exec. Can we not deprecate this function?

**Comment by nadar** [comment]
@mzummo  We could switch visibility of exec() from protected to public, but for what example are u using _exec() can you make an example? Please provide example code.

**Comment by nadar** [comment]
I am going to close this issue because:

- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.
