### ISSUE TITLE
Lib agent

### ISSUE THREAD

**Issue by mbalandis** [php-mod/curl#61]
in version 2.2.0
in the src agent still tells it is 1.9

```
const USER_AGENT = 'PHP Curl/1.9 (+https://github.com/php-mod/curl)';
```

It is not a bug, however, when I tail logs I wanted to check if it updated correctly but it cannot be checked by this. Maybe it just need a change to 
```
const USER_AGENT = 'PHP Curl/2.0 (+https://github.com/php-mod/curl)';
```

Also just to confirm, no breaking changes were made (except for php 5.5 removal of course) when transitioning from 1.* to 2.* ? Will nothing breaking gonna be changed continuing with 2.* ? I would suggest jump to 3.* if something breaking gonna be done. Let me know if there is something I need to keep an eye out.

Thanks :)

**Comment by nadar** [comment]
I will take care of the user agent version. Also the library follows semver and should only contain breaks when releasing major versions.
