### ISSUE TITLE
Verbose mode is not working

### ISSUE THREAD

**Issue by jokaorgua** [php-mod/curl#68]
Verbose mode is not working because of $this->setOpt(CURLINFO_HEADER_OUT, true); in init function.
even if you will try to set to false verbose will not work. you must not set it at all if you need verbose output.

**Comment by nadar** [comment]
So you would recommend an option where this can be configured?

**Comment by jokaorgua** [comment]
2 years have passed :) I do not remember the context of this issue.

**Comment by nadar** [comment]
sure, i understand :-) Thanks anyway for reporting.
