### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by nadar** [php-mod/curl#71]
@amouhzi We should change or remove php version restrictions, since php 8 has been released.

https://github.com/php-mod/curl/blob/master/composer.json#L24

**Comment by nadar** [comment]
@amouhzi would you accept a PR? This is a very urgent topic i would say! Thanks for reply.

**Comment by nadar** [comment]
@amouhzi any news on this?! i think this is still very urgent!

**Comment by strawoo** [comment]
> @amouhzi any news on this?! i think this is still very urgent!

I agree. This PR needs to be resolved quickly

**Comment by nadar** [comment]
This library should have more maintainers, i already offered @amouhzi to help work on this library. Such a popular library must have more maintainers in case of emergency!

**Comment by amouhzi** [comment]
Thank you all. and sorry for my late intervention. You're right, this library needs more maintainers.
